# Generated by Django 5.0.6 on 2024-06-20 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_verify_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='employeeduty',
            old_name='duty',
            new_name='duty_in_role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AlterField(
            model_name='employeeduty',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent_verify_app.rolehistory'),
        ),
        migrations.AddField(
            model_name='company',
            name='department',
            field=models.ManyToManyField(to='talent_verify_app.departments'),
        ),
        migrations.DeleteModel(
            name='CompanyDepartments',
        ),
    ]
