# Generated by Django 5.0.6 on 2024-06-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_verify_app', '0005_remove_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_in_role', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='rolehistory',
            name='duties',
            field=models.ManyToManyField(to='talent_verify_app.dutyrole'),
        ),
        migrations.DeleteModel(
            name='EmployeeDuty',
        ),
    ]
