# Generated by Django 5.0.6 on 2024-06-23 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_verify_app', '0007_rolehistory_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_hist', to='talent_verify_app.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_company_hist', to='talent_verify_app.employee')),
            ],
        ),
    ]
