# Generated by Django 5.0.6 on 2024-06-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_verify_app', '0010_alter_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': []},
        ),
    ]
